'use client'

import Link from 'next/link'
import { useLocale } from 'next-intl'
import { motion } from 'framer-motion'
import {
  Shield,
  FileCheck,
  Award,
  Users,
  CheckCircle2,
  Eye,
  Scale,
  ArrowRight,
  Building,
  RefreshCw,
} from 'lucide-react'
import { type Locale } from '@/i18n/config'

const content = {
  es: {
    badge: 'Transparencia',
    title: 'Transparencia total',
    description: 'Somos la empresa más transparente del mercado del aislamiento. Sin letra pequeña, sin costes ocultos, sin sorpresas. Aquí tienes toda la información.',
    companyTitle: 'Información de la empresa',
    companyDesc: 'Datos verificables de nuestra empresa.',
    companyItems: [
      { label: 'Razón social', value: 'Verdenomia S.L.' },
      { label: 'CIF', value: 'B22963375' },
      { label: 'Empresa registrada', value: 'Registro Mercantil de Alicante' },
      { label: 'Seguro RC', value: 'Seguro de responsabilidad civil vigente' },
    ],
    aislaTitle: 'Cumplimiento AISLA',
    aislaDesc: 'Seguimos todas las recomendaciones de AISLA (Asociación de Instaladores de Aislamiento) para garantizar un servicio de calidad.',
    aislaItems: [
      'Comunicación en castellano nativo, sin traducciones automáticas',
      'Sin uso de logotipos no autorizados de organismos públicos',
      'Contratos claros y legibles antes de la firma',
      'Técnicos formados y cualificados para cada intervención',
      'Materiales certificados con fichas técnicas disponibles',
    ],
    caeTitle: '¿Cómo funciona el CAE de forma transparente?',
    caeDesc: 'El intercambio CAE explicado con total claridad.',
    caeGive: 'Lo que tú aportas',
    caeGiveItems: [
      'Certificados de Ahorro Energético (CAE) generados por la mejora de tu vivienda',
      'Estos certificados representan el ahorro energético conseguido',
      'Son un documento administrativo, no un coste económico',
    ],
    caeGet: 'Lo que tú recibes',
    caeGetItems: [
      'Aislamiento profesional de tu suelo de buhardilla',
      'Materiales de primera calidad con garantía de 25 años',
      'Intervención completa sin ningún coste para ti',
    ],
    caeNote: 'Sin costes ocultos. Sin compromisos futuros. Sin sorpresas.',
    commitmentsTitle: 'Nuestros compromisos',
    commitmentsDesc: 'Cinco compromisos que nos diferencian en el mercado.',
    commitments: [
      { title: 'Contrato legible', desc: 'Recibes el contrato antes de firmar, con tiempo para leerlo y hacer preguntas. Sin presión.' },
      { title: 'Fotos reales del trabajo', desc: 'Te proporcionamos fotos reales de cada intervención. Sin fotos de stock ni imágenes genéricas.' },
      { title: 'Técnicos cualificados', desc: 'Todos nuestros técnicos están formados y certificados para realizar las intervenciones.' },
      { title: 'Garantía 25 años', desc: 'Nuestros materiales están garantizados durante 25 años. Una inversión a largo plazo.' },
      { title: 'Respuesta en 24h', desc: 'Un asesor te contacta en menos de 24 horas tras tu solicitud. Sin esperas innecesarias.' },
    ],
    teamTitle: 'Nuestro equipo',
    teamDesc: 'Más de 50 técnicos certificados trabajando en toda España para ofrecer un servicio de calidad.',
    teamStat: '50+',
    teamStatLabel: 'Técnicos certificados en toda España',
    ctaTitle: '¿Quieres comprobarlo tú mismo?',
    ctaDesc: 'Verifica tu elegibilidad al programa CAE. Sin compromiso, sin costes ocultos.',
    cta: 'Verificar mi elegibilidad',
  },
  en: {
    badge: 'Transparency',
    title: 'Total transparency',
    description: 'We are the most transparent company in the insulation market. No fine print, no hidden costs, no surprises. Here is all the information.',
    companyTitle: 'Company information',
    companyDesc: 'Verifiable data about our company.',
    companyItems: [
      { label: 'Company name', value: 'Verdenomia S.L.' },
      { label: 'Tax ID (CIF)', value: 'B22963375' },
      { label: 'Registered company', value: 'Commercial Registry of Alicante' },
      { label: 'Liability insurance', value: 'Active civil liability insurance' },
    ],
    aislaTitle: 'AISLA compliance',
    aislaDesc: 'We follow all recommendations from AISLA (Association of Insulation Installers) to guarantee quality service.',
    aislaItems: [
      'Communication in native Spanish, no automatic translations',
      'No unauthorized use of public body logos',
      'Clear and legible contracts before signing',
      'Trained and qualified technicians for each intervention',
      'Certified materials with available technical data sheets',
    ],
    caeTitle: 'How does the CAE work transparently?',
    caeDesc: 'The CAE exchange explained with full clarity.',
    caeGive: 'What you provide',
    caeGiveItems: [
      'Energy Savings Certificates (CAE) generated by the improvement of your home',
      'These certificates represent the energy savings achieved',
      'They are an administrative document, not an economic cost',
    ],
    caeGet: 'What you receive',
    caeGetItems: [
      'Professional insulation of your attic floor',
      'Top-quality materials with a 25-year warranty',
      'Complete intervention at no cost to you',
    ],
    caeNote: 'No hidden costs. No future commitments. No surprises.',
    commitmentsTitle: 'Our commitments',
    commitmentsDesc: 'Five commitments that set us apart in the market.',
    commitments: [
      { title: 'Readable contract', desc: 'You receive the contract before signing, with time to read it and ask questions. No pressure.' },
      { title: 'Real work photos', desc: 'We provide real photos of each intervention. No stock photos or generic images.' },
      { title: 'Qualified technicians', desc: 'All our technicians are trained and certified to perform the interventions.' },
      { title: '25-year warranty', desc: 'Our materials are guaranteed for 25 years. A long-term investment.' },
      { title: '24h response', desc: 'An advisor contacts you within 24 hours of your request. No unnecessary waits.' },
    ],
    teamTitle: 'Our team',
    teamDesc: 'Over 50 certified technicians working across Spain to deliver quality service.',
    teamStat: '50+',
    teamStatLabel: 'Certified technicians across Spain',
    ctaTitle: 'Want to see for yourself?',
    ctaDesc: 'Check your eligibility for the CAE program. No commitment, no hidden costs.',
    cta: 'Check my eligibility',
  },
}

export default function TransparenciaPage() {
  const locale = useLocale() as Locale
  const t = content[locale]
  const commitmentIcons = [FileCheck, Eye, Award, Shield, RefreshCw]
  const companyIcons = [Building, FileCheck, Scale, Shield]

  return (
    <div className="overflow-hidden">
      {/* Hero */}
      <section className="relative py-24 bg-gray-900 overflow-hidden">
        <div className="container-custom relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-sm rounded-full text-verde-100 text-sm mb-6">
              <Eye className="w-4 h-4" />
              {t.badge}
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-display font-bold text-white leading-tight mb-6">
              {t.title}
            </h1>
            <p className="text-xl text-verde-100 mb-8 leading-relaxed">
              {t.description}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Company info */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-display font-bold text-verde-900 mb-4">
              {t.companyTitle}
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">{t.companyDesc}</p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-4xl mx-auto">
            {t.companyItems.map((item, index) => {
              const Icon = companyIcons[index]
              return (
                <motion.div
                  key={item.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="bg-verde-50 rounded-2xl p-6 text-center"
                >
                  <div className="w-14 h-14 mx-auto mb-4 bg-verde-100 rounded-2xl flex items-center justify-center">
                    <Icon className="w-7 h-7 text-verde-600" />
                  </div>
                  <p className="text-sm text-gray-500 mb-1">{item.label}</p>
                  <p className="font-bold text-verde-800">{item.value}</p>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      {/* AISLA compliance */}
      <section className="py-20 bg-verde-50">
        <div className="container-custom">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-3xl md:text-4xl font-display font-bold text-verde-900 mb-4">
                {t.aislaTitle}
              </h2>
              <p className="text-lg text-gray-600 mb-8">{t.aislaDesc}</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <div className="space-y-4">
                {t.aislaItems.map((item, i) => (
                  <div key={i} className="flex items-start gap-3 bg-white rounded-xl p-4">
                    <CheckCircle2 className="w-5 h-5 text-verde-500 mt-0.5 flex-shrink-0" />
                    <span className="text-gray-700">{item}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* How CAE works */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-display font-bold text-verde-900 mb-4">
              {t.caeTitle}
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">{t.caeDesc}</p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="bg-gray-900 rounded-3xl p-8 text-white"
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-white/10 rounded-lg flex items-center justify-center">
                  <Scale className="w-5 h-5 text-verde-300" />
                </div>
                <h3 className="text-xl font-bold">{t.caeGive}</h3>
              </div>
              <div className="space-y-4">
                {t.caeGiveItems.map((item, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-verde-400 mt-0.5 flex-shrink-0" />
                    <span className="text-verde-100">{item}</span>
                  </div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="bg-verde-600 rounded-3xl p-8 text-white"
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center">
                  <Award className="w-5 h-5 text-white" />
                </div>
                <h3 className="text-xl font-bold">{t.caeGet}</h3>
              </div>
              <div className="space-y-4">
                {t.caeGetItems.map((item, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-verde-200 mt-0.5 flex-shrink-0" />
                    <span className="text-verde-50">{item}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>

          <motion.p
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mt-8 text-lg font-semibold text-verde-700"
          >
            {t.caeNote}
          </motion.p>
        </div>
      </section>

      {/* Commitments */}
      <section className="py-20 bg-verde-50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-display font-bold text-verde-900 mb-4">
              {t.commitmentsTitle}
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">{t.commitmentsDesc}</p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {t.commitments.map((commitment, index) => {
              const Icon = commitmentIcons[index]
              return (
                <motion.div
                  key={commitment.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="bg-white rounded-2xl p-6 shadow-sm"
                >
                  <div className="w-14 h-14 bg-verde-100 rounded-2xl flex items-center justify-center mb-4">
                    <Icon className="w-7 h-7 text-verde-600" />
                  </div>
                  <h3 className="text-lg font-bold text-verde-800 mb-2">{commitment.title}</h3>
                  <p className="text-gray-600">{commitment.desc}</p>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      {/* Team */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center max-w-2xl mx-auto"
          >
            <div className="w-20 h-20 mx-auto mb-6 bg-verde-100 rounded-3xl flex items-center justify-center">
              <Users className="w-10 h-10 text-verde-600" />
            </div>
            <h2 className="text-3xl md:text-4xl font-display font-bold text-verde-900 mb-4">
              {t.teamTitle}
            </h2>
            <p className="text-xl text-gray-600 mb-8">{t.teamDesc}</p>
            <div className="inline-flex items-center gap-3 bg-verde-50 rounded-2xl px-8 py-4">
              <span className="text-4xl font-bold text-verde-700">{t.teamStat}</span>
              <span className="text-gray-600 text-left">{t.teamStatLabel}</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-gradient-to-b from-white to-gray-50">
        <div className="container-custom text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl md:text-4xl font-display font-bold text-gray-900 mb-6">{t.ctaTitle}</h2>
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">{t.ctaDesc}</p>
            <Link href={`/${locale}#eligibilidad`} className="btn-primary text-lg px-8 py-4">
              {t.cta}
              <ArrowRight className="w-5 h-5" />
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
